add tags coditions

diff --git a/.github/workflows/github-actions-tracker.yml b/.github/workflows/github-actions-tracker.yml
--- a/.github/workflows/github-actions-tracker.yml
+++ b/.github/workflows/github-actions-tracker.yml
@@ -1,6 +1,10 @@
 name: GitHub Actions Tracker
 on:
   workflow_dispatch:
+    inputs:
+      tag_name:
+        description: "GitHub Actions Tracker"
+        required: true
   release:
     types: [published]
 
@@ -11,7 +15,15 @@ jobs:
     steps:
       # This step builds a var with the release tag value to use later
       - name: Set Release Version from Tag
-        run: echo "RELEASE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
+        run: |
+          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
+            echo "RELEASE_VERSION=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
+          elif startsWith("${{ github.ref }}", "refs/tags/"); then
+            echo "RELEASE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
+          else
+            echo "Error: No valid tag found."
+            exit 1
+          fi
       # This step creates a new GitHub Actions Tracker for App123
       - name: Carts
         uses: newrelic/deployment-marker-action@v2.3.0
